/* Main.c file generated by New Project wizard
 *
 * Created:   mer. févr. 17 2016
 * Processor: PIC16F887
 * Compiler:  MPLAB XC8
 */

#include <xc.h>

// CONFIG1
#pragma config FOSC = INTRC_CLKOUT// Oscillator Selection bits (INTOSC oscillator: CLKOUT function on RA6/OSC2/CLKOUT pin, I/O function on RA7/OSC1/CLKIN)
#pragma config WDTE = OFF       // Watchdog Timer Enable bit (WDT disabled and can be enabled by SWDTEN bit of the WDTCON register)
#pragma config PWRTE = OFF      // Power-up Timer Enable bit (PWRT disabled)
#pragma config MCLRE = ON       // RE3/MCLR pin function select bit (RE3/MCLR pin function is MCLR)
#pragma config CP = OFF         // Code Protection bit (Program memory code protection is disabled)
#pragma config CPD = OFF        // Data Code Protection bit (Data memory code protection is disabled)
#pragma config BOREN = OFF      // Brown Out Reset Selection bits (BOR disabled)
#pragma config IESO = OFF       // Internal External Switchover bit (Internal/External Switchover mode is disabled)
#pragma config FCMEN = OFF      // Fail-Safe Clock Monitor Enabled bit (Fail-Safe Clock Monitor is disabled)
#pragma config LVP = OFF        // Low Voltage Programming Enable bit (RB3 pin has digital I/O, HV on MCLR must be used for programming)

// CONFIG2
#pragma config BOR4V = BOR40V   // Brown-out Reset Selection bit (Brown-out Reset set to 4.0V)
#pragma config WRT = OFF        // Flash Program Memory Self Write Enable bits (Write protection off)

#define _XTAL_FREQ 4000000

#define pushed   0
#define released 1
#define empty 1
#define not_empty 0
#define ON 0
#define OFF 1

#define button PORTBbits.RB0
#define sensor PORTBbits.RB1
#define motor  PORTBbits.RB2
#define LED_ET PORTDbits.RD0
#define LED_MP PORTDbits.RD1
#define Trigger PORTCbits.RC0
#define Echo PORTBbits.RB4


unsigned char last_button, pushed_button, latched_PORTB4;
unsigned int d;

void main(void)
 {
    OSCCON&=0b11101110;// use internal oscillator
    OSCCON|=0b01100000;// set it to 4 Mhz
    
    TRISD=0x00;// configure PORTD as output
    PORTD=0x00;// initialize PORTD to 0x00 :All LEDs are OFF
    ANSELH=0x00;// All RB pins are digital
    OPTION_REGbits.nRBPU=0;
    WPUBbits.WPUB1=1;    
    TRISBbits.TRISB0=1;
    TRISBbits.TRISB1=1;
    TRISBbits.TRISB2=0;
    TRISCbits.TRISC0=0;//Trigger as Output
    TRISB4=1;// Echo input
    
    IOCB4=1;// Activer RB4 comme source d'évennement pour l'interruption RB
    RBIF=0;// effacer indicateur RB
    RBIE=1;// activer interruption RB
    GIE=1;// activation globale des interruptions
    
    motor=OFF;
    LED_ET=0;
    LED_MP=0;
    last_button=button;
    pushed_button=0;
    
    T1CON=0x00;
    // Write your code here
   while (1)
   {
      if((last_button==released) && (button==pushed)) pushed_button=1;
      last_button=button;
      
      if (sensor==empty)LED_ET=1;
	  else LED_ET=0;
	    
      if (pushed_button)
      {
        pushed_button=0;
	 if(sensor==empty)
	 {  while(sensor==empty)
	    {
	       LED_ET=~LED_ET;
	     __delay_ms(500);   
	       }
	  }
	  else
	  {
	     LED_MP=1;
	     motor=ON;
	     while(sensor==not_empty);
	     LED_MP=0;
	     motor=OFF;
	   }
	   }
      /* send a pulse to the Ultrasound module via Trigger pin*/
      TMR1L=0x00;// reset TMR1 count registers
      TMR1H=0x00;
      Trigger=1;// rise Trigger to 1
      __delay_us(10);// delay of 10 us 
      Trigger=0;// reset Trigger
      __delay_ms(60); // delay of 60 ms
      
   }
 }
void interrupt gestionnaire_int(void)
{
if (RBIE&&RBIF)// vérifier si l'origine d'interruption est RB
    {
      latched_PORTB4=(PORTB&0x10)>>4;
       if(latched_PORTB4==1)// rising edge detected
       {
	  TMR1ON=1;// Start TMR1
	  }
       else// falling edge detected
       {
	  TMR1ON=0;// Stop TMR1
	  d=TMR1L|(TMR1H<<8);// calculate the TMR1 counter register
          d=(unsigned int)(d/58.82);// calculate the distance in cm
	  }
       RBIF=0; // Effacer indicateur d'interruption RB
    }
}